### ISSUE TITLE
Error in Both the Xamarin and WPF Sample apps

### ISSUE THREAD

**Issue by MickCG** [AlyElHaddad/ThunderboltIoc#1]
After fixing a mysterious path problem in Java in the Development Kit Location path.  I updated and ran both and get the following error:
System.InvalidOperationException
  Message=Unable to locate a registered implementation for a service of type 
  'ThunderboltIocSamples.XamarinForms.ViewModels.MainViewModel'.

I suspect it is the ThunderboltServiceLifetime in the SharedServiceRegistration.cs. Not knowing Regex that well not sure where it is exactly.

**Comment by AlyElhaddad** [comment]
This exception indicates that source generation did not occur properly for the mentioned service. The reason this could happen for `MainViewModel` in the sample case is that `MainViewModel` itself is not registered properly. My hypothesis is that you have changed your regex. The error message indicates that the `MainViewModel` is in the `ThunderboltIocSamples.XamarinForms.ViewModels` namespace. The regex provided in the sample as-is, covers this namespace. Would you please fallback to the original regex and let me know if this helps?

**Comment by MickCG** [comment]
I will look into it but it won't be till around 6:00 pm pacific time. But I
do not believe I changed the regex file intentionally?

**Comment by MickCG** [comment]
I finally got back to trying things. I decided to create a new project called MyThunder. My viewmodels are in a folder called View Models. My MainViewModel has a namespace like: namespace MyThunder.ViewModels. I modified the SharedServiceRegistration to the following:
System.InvalidOperationException
  [assembly: ThunderboltRegexInclude(
    ThunderboltServiceLifetime.Transient,
    regex: @"(global::)?(MyThunder\.ViewModels)\.[A-Z][A-z_]+ViewModel")]
And am still getting the same error Unable to locate a registered implementation for service of type 'MyThunder.ViewModels.MainViewModel' Any ideas

**Comment by AlyElhaddad** [comment]
Although @"\." should be used instead of "." when matching the dot (.) character in regular expressions, the regex you suggested should be working with the namespace you provided anyway (because an un-escaped dot means any character including a dot). Have you made sure that you have a **partial** class in your project that inherits `ThunderboltRegistration`, and that that partial class does get attached to the container during the runtime via `ThunderboltActivator.Attach<YourClassName>();` ?

If so, please attach a sample of the problem for me to examine.

**Comment by AlyElhaddad** [comment]
@MickCG would you please let me know if this is still a problem?

**Comment by MickCG** [comment]
Yes, I went through the app checking that it was identical to the Xamarin sample repository. The RegEx matches the original, etc. And still got the error, that is why I thought I'd take a shot at the WPF sample after cloning it as I said, no changes at all and got the not found in the dicionary.

**Comment by AlyElhaddad** [comment]
@MickCG would you please attach a copy of your solution?

**Comment by MickCG** [comment]
Here you go:
[https://github.com/MickCG/ThunderboltIocSaples.WPF.git](url)

**Comment by AlyElhaddad** [comment]
@MickCG  Thank you for your continuous help in finding mistakes in order to make this better. I have updated a local copy of your solution to version `1.2.3` and it now works. Would you please verify?

**Comment by MickCG** [comment]
The 1.2.3 version does now work in the WPF example. I updated my app that I copied and pasted MyThunder a Xamarin.Forms app. There I am still getting the same not in Dictionary error.

**Comment by AlyElhaddad** [comment]
@MickCG  I'm aware that sometimes, Android projects fail to deploy on emulators due to too long paths. I've updated the samples; pumped their version to `1.2.3` and used more compact folders, names, and namespaces. Could you verify that a fresh copy of the Xamarin sample does work?

**Comment by MickCG** [comment]
OK here is what I did. I deleted the folder I had of ThunderboltIoc. This is in the root of my drive C:, I too thought about long paths. Next, I checked the NuGet packages, and there were updates forNETCore.Universal... and for I think Xamarin.Forms. I complied with no errors, then ran it on a connected Android phone, and the same error. 
'ThunderForms.ViewModels.MainViewModel' was not present in the dictionary.

**Comment by AlyElhaddad** [comment]
Things you may try:
- Delete bin and obj directories in all of your projects.
- Clean and rebuild the solution.
- Restart visual studio.

If none of that work, please provide a copy of your local solution in which the problem is reproduceable.

**Comment by MickCG** [comment]
OK moved the Xamarin sample to the root, cleaned etc. and rebuild and got the error:
System.Collections.Generic.KeyNotFoundException
  Message=The given key 'ThunderForms.ViewModels.MainViewModel' was not present in the dictionary.

Github repository: [https://github.com/MickCG/XamarinForms.git](url)

**Comment by AlyElhaddad** [comment]
I have literally downloaded the solution locally and ran the Android project without changing anything and it worked. I was thinking maybe it's some environment issue that is preventing the source generator from working but the fact that it worked with you in WPF rules out that possibility.

There should be at least one of four (might be more?) reasons for the error message you shared:
1. The source generator did not generate any source code at all because of an error during the generation process. To make sure that this is the case, check your build output window for the following message:
    > Generator 'ThunderboltSourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result.
2. The source generator did not generate any source code at all because it failed to find any relevant registrations.
    To solve this:
    - Make sure that the `SharedServiceRegistration` class has the `partial` modifier (which it does).
    - Make sure that your startup routine includes a call to `ThunderboltActivator.Attach<SharedServiceRegistration>();` (which it does in the static constructor of `App`).
    - Make sure that the regular expression provided in `ThunderboltRegexInclude` can match your type's name including its full namespace (`ThunderForms.ViewModels.MainViewModel`, which it does).
3. You might be enabling a linker or an optimizer that removes the call to the static constructor (which includes `ThunderboltActivator.Attach<SharedServiceRegistration>();`) before the compilation phase.
    To rule this out: Try running the app in DEBUG mode while the linker is set to `None` or `--nolink`.
4. Projects that reference source generators -in general- must be written in C# version `9.0` or higher.
    To make sure that this is the case:
    - Add `<LangVersion>9.0</LangVersion>` inside the `PropertyGroup` section in your project files (both, `ThunderForms.csproj` and `ThunderDroid.csproj` (I'm assuming that you're trying to run the Android project)).

**Comment by AlyElhaddad** [comment]
@MickCG I'd appreciate letting me know whether or not that worked for you.

**Comment by MickCG** [comment]
OK, I have it working. All of the 1 - 3 were OK. The one that had not been done was the version 9.0 added. But The app does not work on Visual Studio 2017 it does seem to work only on 2022 or at least for me.

**Comment by AlyElhaddad** [comment]
Thank you for letting me know. Please note that C# 9 needs at least Visual Studio 2022 or Visual Studio 2019 `v16.7` (or higher). I have documented that and updated the samples accordingly.
